var_to_lbl <- function(df, col) {
  
  df_lbl <- df %>%
    mutate(lbl = case_when(
      {{col}} == "AGEENTRY" ~ "Age",
      {{col}} == "GENDER" ~ "Sex",
      {{col}} == "VMIN" ~ "Ethnicity",
      {{col}} == "FIQ" ~ "IQ",
      {{col}} == "EDUC_NUM" ~ "Education",
      {{col}} == "NEET" ~ "Employement",
      {{col}} == "INDPT" ~ "Housing",
      {{col}} == "REL" ~ "Relationship",
      {{col}} == "HOLLTOTP" ~ "Socioeconomic status",
      {{col}} == "PAS_tot2" ~ "Premorbid functioning",
      {{col}} == "AGEONSET" ~ "Onset",
      {{col}} == "DUPONSET" ~ "Duration of untreated psychosis",
      {{col}} == "DUI" ~ "Duration of untreated illness",
      {{col}} == "MODE" ~ "Mode of onset",
      {{col}} == "CAYRCONV" ~ "Clinical high-risk transition",
      {{col}} == "IP_OP" ~ "in/out patient status",
      {{col}} == "DX_B2" ~ "Diagnosis",
      {{col}} == "SUD" ~ "Substance use disorder",
      str_starts({{col}}, "EDUC") ~ "EDUCATION",
      str_starts({{col}}, "SOFAS") ~ "Functioning",
      str_starts({{col}}, "SAPS") ~ "Severity of positive symptoms",
      str_starts({{col}}, "SANS") ~ "Severity of negative symptoms",
      str_starts({{col}}, "HAS") ~ "Anxiety symptoms",
      str_starts({{col}}, "CDS") ~ "Depression symptoms",
      str_starts({{col}}, "YMRS") ~ "Mania symptoms",
      str_starts({{col}}, "CD8") ~ "Suicidal ideation",
      str_starts({{col}}, "SUMD1") ~ "Insight",
      str_starts({{col}}, "CPZW") ~ "Chlorpromazine equivalent",
      str_starts({{col}}, "COMP") ~ "Adherence",
      str_starts({{col}}, "JSR_\\d+") ~ "Remission of joint symptoms", 
      str_starts({{col}}, "PSR_\\d+") ~ "Remission of positive symptoms", 
      str_starts({{col}}, "NSR_\\d+") ~ "Remission of negative symptoms",
      str_starts({{col}}, "RECOV") ~ "Recovery",
      {{col}} == "JSR_1ST" ~ "Time to remission of joint symptoms", 
      {{col}} == "PSR_1ST" ~ "Time to remission of positive symptoms", 
      {{col}} == "NSR_1ST" ~ "Time to remission of negative symptoms",
      {{col}} == "JSR_BY3" ~ "Early remission of joint symptoms", 
      {{col}} == "PSR_BY3" ~ "Early remission of positive symptoms", 
      {{col}} == "NSR_BY3" ~ "Early remission of negative symptoms",
      {{col}} == "VERM_Z" ~ "Verbal memory", 
      {{col}} == "WM_Z" ~ "Working memory",
      {{col}} == "EF_Z" ~ "Executive functioning",
      {{col}} == "SOP_Z" ~ "Speed of processing",
      {{col}} == "VISM_Z" ~ "Visual memory",
      {{col}} == "VA_Z" ~ "Visual attention",
      {{col}} == "SC_Z" ~ "Social cognition",
      {{col}} == "TXM0CO" ~ "Court-ordered treatment"
    ))
  return(df_lbl)
}
